config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
         :skip => [:registrations]

  devise_scope :user do
    get "user/sign_up", to: "users/registrations#new", as: :new_user_registration
    post "user/sign_up", to: "users/registrations#create", as: :user_registration
  end

  root 'welcome#index'
  match '/404', to: 'errors#not_found', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all
  resources :personal_infos, only: [:new, :edit]
  resources :address_infos, only: [:new, :edit]
  resources :work_infos, only: [:new, :edit]
  resources :education_infos, only: [:new, :edit]
  resources :project_infos, only: [:new, :edit]
  resources :resumes, only: [:show]
  resources :welcome, only: [:destroy]
  get 'settings', to: 'welcome#settings'
  get 'about', to: 'welcome#about'
  get 'privacy_policy', to: 'welcome#privacy_policy'
  get 'add_new_education', to: 'education_infos#add_new_education'
  get 'add_new_work', to: 'work_infos#add_new_work'
  get 'add_new_project', to: 'project_infos#add_new_project'
  get 'delete_education', to: 'education_infos#delete_education'
  get 'delete_work', to: 'work_infos#delete_work'
  get 'delete_project', to: 'project_infos#delete_project'
  get 'skip_continue', to: 'project_infos#skip_continue'
  post '/personal_infos/new', to: 'personal_infos#create', as: 'create_personal_infos'
  post '/personal_infos/:id/edit', to: 'personal_infos#update', as: 'update_personal_infos'
  post '/address_infos/new', to: 'address_infos#create', as: 'create_address_infos'
  post '/address_infos/:id/edit', to: 'address_infos#update', as: 'update_address_infos'
  post '/education_infos/new', to: 'education_infos#create', as: 'create_education_infos'
  post '/education_infos/:id/edit', to: 'education_infos#update', as: 'update_education_infos'
  post '/work_infos/new', to: 'work_infos#create', as: 'create_work_infos'
  post '/work_infos/:id/edit', to: 'work_infos#update', as: 'update_work_infos'
  post '/project_infos/new', to: 'project_infos#create', as: 'create_project_infos'
  post '/project_infos/:id/edit', to: 'project_infos#update', as: 'update_project_infos'
# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/project_infos_controller.rb
# frozen_string_literal: true

class ProjectInfosController < ApplicationController
  before_action :initialize_error_messages, only: %i[new edit create update]
  before_action :initialize_project_infos, only: %i[new edit]

  def new; end

  def edit; end

  def create
    if registration_succeeded?
      flash[:notice] = t('project_infos.information_saved')
      redirect_to root_path
    else
      render 'new'
    end
  end

  def update
    if registration_succeeded?
      flash[:notice] = t('project_infos.update_success_message')
      redirect_to root_path
    else
      render 'edit'
    end
  end

  def add_new_project
    @index = params[:project_index]
    respond_to do |format|
      format.js { render partial: 'project_infos/add_project' }
    end
  end

  def delete_project
    @index = params[:project_index]
    respond_to do |format|
      format.js { render partial: 'project_infos/delete_project' }
    end
  end

  def skip_continue
    flash[:notice] = t('project_infos.information_saved')
    redirect_to root_path
  end

  private

  def project_params(params)
    params.permit(:title, :description)
  end

  def initialize_error_messages
    @error_messages = []
  end

  def initialize_project_infos
    if current_user.projects.exists?
      @projects = current_user.projects
      @record_count = @projects.ids.length
    else
      @projects = []
      @record_count = 0
    end
  end

  def error_messages(error_record)
    error_record.errors.full_messages.each do |msg|
      @error_messages.push(msg)
    end
  end

  def set_project_records
    @projects = []
    params[:projects].each do |_id, attributes|
      @projects.push(current_user.projects.new(project_params(attributes)))
    end
    @projects
  end

  def registration_succeeded?
    submitting_records = set_project_records
    success = []
    Project.transaction do
      current_user.projects.delete_all if current_user.projects.exists?
      success = submitting_records.map(&:save)
      unless success.all?
        errored = submitting_records.reject { |record| record.errors.blank? }
        errored.each { |error_record| error_messages(error_record) }
        raise ActiveRecord::Rollback
      end
    end
    @error_messages.uniq!
    success.all?
  end
end

app/helpers/project_infos_helper.rb
# frozen_string_literal: true

module ProjectInfosHelper
end

app/views/project_infos/_add_project.js.erb
document.getElementById('newproject').insertAdjacentHTML('beforeend', '<%= j render 'project_infos/project.html' %>');
if(++document.getElementById('submittingrecordcount').value > "0"){
    document.getElementById('submit').style.display = "block";
}

app/views/project_infos/_delete_project.js.erb
document.getElementById('projects<%= @index %>').remove();
if(--document.getElementById('submittingrecordcount').value == 0){
    document.getElementById('submit').style.display = "none";
}

app/views/project_infos/_form.html.erb
<% @projects.each.with_index(1) do |project,index| %>
    <div id="projects<%= index %>">
        <div class="form-group row">
            <div class="col-sm-6 mb-3 mb-sm-0">
                <span class="required-input">
                    <%= text_field_tag "projects[#{index}][title]", project.title, 
                        class: 'form-control form-control-user', placeholder: t('project_infos.project_title') %>
                </span>
            </div>
        </div>
        
        <div class="form-group">
            <span class="required-input">
                <%= text_area_tag "projects[#{index}][description]", project.description,  size: "30x5",
                    class: 'form-control form-control-textarea', placeholder: t('project_infos.project_description') %>
            </span>
        </div>
        <div class="form-group row">
            <div class="col-sm-12 ">
                <%= link_to t('project_infos.delete_button'), delete_project_path(:project_index => index),
                    method: :get ,remote: true, name: 'delete_button', class: 'btn btn-secondary btn-user float-right' %>
            </div>
        </div>
        <hr>
    </div>
    <% if @projects.last == project %>
        <div id="newproject">
        </div>
    <% end %>
<% end %>
<%= hidden_field_tag 'submittingrecordcount', @record_count %>
<%= hidden_field_tag 'projectindex', @record_count %>
<% if @projects.empty?() %>
    <div id="newproject">
    </div>
<% end %>

app/views/project_infos/_project.html.erb
<div id="projects<%= @index %>">
    <div class="form-group row">
        <div class="col-sm-6 mb-3 mb-sm-0">
            <span class="required-input">
                <input type="text" name="projects[<%= @index %>][title]" id="projects_<%= @index %>_title"
                class="form-control form-control-user" placeholder="<%= t('project_infos.title') %>"/>
            </span>
        </div>
   </div>

    <div class="form-group">
        <span class="required-input">
            <textarea name="projects[<%= @index %>][description]" id="projects_<%= @index %>_description"  rows="5" cols="30"
            class="form-control form-control-textarea"  placeholder="<%= t('project_infos.project_description') %>"></textarea>
        </span>
    </div>

    <div class="form-group row">
        <div class="col-sm-12 ">
            <%= link_to t('project_infos.delete_button'), delete_project_path(:project_index => @index),
                         method: :get ,remote: true, name: 'delete_button', class: 'btn btn-secondary btn-user float-right' %>
        </div>
    </div>
    <hr>
</div>

app/views/project_infos/edit.html.erb
<%= render 'layouts/multiple_record_errors', obj: @error_messages %>
<h1 class="h4 text-gray-900 mb-4"><%= t('project_infos.title')%></h1>
<%= form_tag update_project_infos_path(method: :post) do %>
    <%= render 'project_infos/form' %>
    <div class="form-group row">
        <div class="col-sm-12 ">
            <%= button_tag t('project_infos.add_button'), type: 'button', onclick: 'addProject()', class: 'btn btn-secondary' %>
            <%= submit_tag t('common.submit'), id: 'submit', class: 'btn btn-secondary btn-user float-right', style: @projects.empty?() ? "display:none" : "" %>
        </div>
    </div>
<% end %>

app/views/project_infos/new.html.erb
<%= render 'layouts/multiple_record_errors', obj: @error_messages %>
<h1 class="h4 text-gray-900 mb-4"><%= t('project_infos.title')%></h1>
<%= form_tag create_project_infos_path(method: :post) do %>
    <%= render 'project_infos/form' %>
    <div class="form-group row">
        <div class="col-sm-12 ">
            <%= button_tag t('project_infos.add_button'), type: 'button', onclick: 'addProject()', class: 'btn btn-secondary' %>
            <%= submit_tag t('common.submit'), id: 'submit', class: 'btn btn-secondary btn-user float-right', style: @projects.empty?() ? "display:none" : "" %>
        </div>
    </div>
    <div class="form-group row">
        <div class="col-sm-12 ">
            <%= link_to t('project_infos.skip_continue'), skip_continue_path, class: 'btn btn-secondary float-right' %>
        </div>
    </div>
<% end %>