config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
         :skip => [:registrations]

  devise_scope :user do
    get "user/sign_up", to: "users/registrations#new", as: :new_user_registration
    post "user/sign_up", to: "users/registrations#create", as: :user_registration
  end

  root 'welcome#index'
  match '/404', to: 'errors#not_found', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all
  resources :personal_infos, only: [:new, :edit]
  resources :address_infos, only: [:new, :edit]
  resources :work_infos, only: [:new, :edit]
  resources :education_infos, only: [:new, :edit]
  resources :project_infos, only: [:new, :edit]
  resources :resumes, only: [:show]
  resources :welcome, only: [:destroy]
  get 'settings', to: 'welcome#settings'
  get 'about', to: 'welcome#about'
  get 'privacy_policy', to: 'welcome#privacy_policy'
  get 'add_new_education', to: 'education_infos#add_new_education'
  get 'add_new_work', to: 'work_infos#add_new_work'
  get 'add_new_project', to: 'project_infos#add_new_project'
  get 'delete_education', to: 'education_infos#delete_education'
  get 'delete_work', to: 'work_infos#delete_work'
  get 'delete_project', to: 'project_infos#delete_project'
  get 'skip_continue', to: 'project_infos#skip_continue'
  post '/personal_infos/new', to: 'personal_infos#create', as: 'create_personal_infos'
  post '/personal_infos/:id/edit', to: 'personal_infos#update', as: 'update_personal_infos'
  post '/address_infos/new', to: 'address_infos#create', as: 'create_address_infos'
  post '/address_infos/:id/edit', to: 'address_infos#update', as: 'update_address_infos'
  post '/education_infos/new', to: 'education_infos#create', as: 'create_education_infos'
  post '/education_infos/:id/edit', to: 'education_infos#update', as: 'update_education_infos'
  post '/work_infos/new', to: 'work_infos#create', as: 'create_work_infos'
  post '/work_infos/:id/edit', to: 'work_infos#update', as: 'update_work_infos'
  post '/project_infos/new', to: 'project_infos#create', as: 'create_project_infos'
  post '/project_infos/:id/edit', to: 'project_infos#update', as: 'update_project_infos'
# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/address_infos_controller.rb
# frozen_string_literal: true

class AddressInfosController < ApplicationController
  def new
    @address = Address.new
  end

  def edit
    @address = Address.where(user_id: current_user.id).first_or_initialize
  end

  def create
    @address = Address.new(address_params)
    @address.user = current_user
    if @address.save
      redirect_to new_education_info_path
    else
      render 'new'
    end
  end

  def update
    @address = Address.where(user_id: current_user.id).first_or_initialize
    if @address.update(address_params)
      flash[:notice] = t('address_infos.update_success_message')
      redirect_to root_path
    else
      render 'edit'
    end
  end

  private

  def address_params
    params.require(:address).permit(:nationality, :province, :city, :remaining_address,
                                    :country, :post_cd, :mail_id, :phone_no,
                                    :linkedIn_url, :twitter_url, :hosting_service, :repository_url)
  end
end

app/helpers/address_infos_helper.rb
# frozen_string_literal: true

module AddressInfosHelper
end

app/views/address_info/new.html.erb
<div id="wrapper">
    
    <!-- Sidebar -->
    <%= render 'welcome/sidebar'%>
    <!-- End of Sidebar -->

    <!-- Content Wrapper -->
    <div id="content-wrapper" class="d-flex flex-column">

        <!-- Main Content -->
        <div id="content">

            <!-- Topbar -->
            <%= render 'welcome/navigationbar'%>
            <!-- End of Topbar -->

            <!-- Begin Page Content -->
            <div class="container-fluid">
                <!--Body Of the Page -->
                <h1 class="h4 text-gray-900 mb-4"><%= t('address.title') %></h1>
                <%= form_with scope: :address, url: address_info_index_path, local: true, html: { class: 'user' } do |f| %>
                    <div class="form-group row">
                        <div class="col-sm-6 mb-3 mb-sm-0">
                            <%= f.text_field :nationality, autofocus: true, class: 'form-control form-control-user',
                            placeholder: t('address.nationality') %>
                        </div>

                        <div class="col-sm-6">
                            <%= f.text_field :province, class: 'form-control form-control-user',
                            placeholder: t('address.province') %>
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class="col-sm-6 mb-3 mb-sm-0">
                            <%= f.text_field :city, autofocus: true, class: 'form-control form-control-user',
                            placeholder: t('address.city') %>
                        </div>

                        <div class="col-sm-6">
                            <%= f.text_field :remaining_address, class: 'form-control form-control-user',
                            placeholder: t('address.remaining_address') %>
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class="col-sm-6 mb-3 mb-sm-0">
                            <%= f.text_field :country, autofocus: true, class: 'form-control form-control-user',
                            placeholder: t('address.current_country') %>
                        </div>

                        <div class="col-sm-6">
                            <%= f.number_field :post_cd, class: 'form-control form-control-user',
                            placeholder: t('address.current_zipcode') %>
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class="col-sm-6 mb-3 mb-sm-0">
                            <%= f.email_field :mail_id, autofocus: true, class: 'form-control form-control-user',
                            placeholder: t('address.mail_id') %>
                        </div>

                        <div class="col-sm-6">
                            <%= f.telephone_field :phone_no, class: 'form-control form-control-user',
                            placeholder: t('address.contact_number') %>
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class="col-sm-6 mb-3 mb-sm-0">
                            <%= f.url_field :linkedIn_url, autofocus: true, class: 'form-control form-control-user',
                            placeholder: t('address.linkedIn_url') %>
                        </div>

                        <div class="col-sm-6">
                            <%= f.url_field :twitter_url, class: 'form-control form-control-user',
                            placeholder: t('address.twitter_url') %>
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class="col-sm-12 ">
                            <%= link_to t('common.back'), new_personal_info_path, class: 'btn btn-secondary btn-user' %>
                            <%= f.submit t('common.next'), class: 'btn btn-secondary btn-user float-right'  %>
                        </div>
                    </div>
                <% end %>
                <!--End Of the Page -->
            </div>
            <!-- End Page Content -->
        </div>
        <!-- End of Main Content -->

        <!-- Footer -->
        <%= render 'welcome/footer' %>
        <!-- End of Footer -->

    </div>
    <!-- End of Content Wrapper -->

</div>
<!-- End of Page Wrapper -->

<!-- Scroll to Top Button-->
<a class="scroll-to-top rounded" href="#page-top">
    <i class="fas fa-angle-up"></i>
</a>

<!-- Logout Modal-->
<%= render 'welcome/logoutModal' %>