config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
         :skip => [:registrations]

  devise_scope :user do
    get "user/sign_up", to: "users/registrations#new", as: :new_user_registration
    post "user/sign_up", to: "users/registrations#create", as: :user_registration
  end

  root 'welcome#index'
  match '/404', to: 'errors#not_found', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all
  resources :personal_infos, only: [:new, :edit]
  resources :address_infos, only: [:new, :edit]
  resources :work_infos, only: [:new, :edit]
  resources :education_infos, only: [:new, :edit]
  resources :project_infos, only: [:new, :edit]
  resources :resumes, only: [:show]
  resources :welcome, only: [:destroy]
  get 'settings', to: 'welcome#settings'
  get 'about', to: 'welcome#about'
  get 'privacy_policy', to: 'welcome#privacy_policy'
  get 'add_new_education', to: 'education_infos#add_new_education'
  get 'add_new_work', to: 'work_infos#add_new_work'
  get 'add_new_project', to: 'project_infos#add_new_project'
  get 'delete_education', to: 'education_infos#delete_education'
  get 'delete_work', to: 'work_infos#delete_work'
  get 'delete_project', to: 'project_infos#delete_project'
  get 'skip_continue', to: 'project_infos#skip_continue'
  post '/personal_infos/new', to: 'personal_infos#create', as: 'create_personal_infos'
  post '/personal_infos/:id/edit', to: 'personal_infos#update', as: 'update_personal_infos'
  post '/address_infos/new', to: 'address_infos#create', as: 'create_address_infos'
  post '/address_infos/:id/edit', to: 'address_infos#update', as: 'update_address_infos'
  post '/education_infos/new', to: 'education_infos#create', as: 'create_education_infos'
  post '/education_infos/:id/edit', to: 'education_infos#update', as: 'update_education_infos'
  post '/work_infos/new', to: 'work_infos#create', as: 'create_work_infos'
  post '/work_infos/:id/edit', to: 'work_infos#update', as: 'update_work_infos'
  post '/project_infos/new', to: 'project_infos#create', as: 'create_project_infos'
  post '/project_infos/:id/edit', to: 'project_infos#update', as: 'update_project_infos'
# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/address_infos_controller.rb
# frozen_string_literal: true

class AddressInfosController < ApplicationController
  def new
    @address = Address.new
  end

  def edit
    @address = Address.where(user_id: current_user.id).first_or_initialize
  end

  def create
    @address = Address.new(address_params)
    @address.user = current_user
    if @address.save
      redirect_to new_education_info_path
    else
      render 'new'
    end
  end

  def update
    @address = Address.where(user_id: current_user.id).first_or_initialize
    if @address.update(address_params)
      flash[:notice] = t('address_infos.update_success_message')
      redirect_to root_path
    else
      render 'edit'
    end
  end

  private

  def address_params
    params.require(:address).permit(:nationality, :province, :city, :remaining_address,
                                    :country, :post_cd, :mail_id, :phone_no,
                                    :linkedIn_url, :twitter_url, :hosting_service, :repository_url)
  end
end

app/helpers/address_infos_helper.rb
# frozen_string_literal: true

module AddressInfosHelper
end

app/views/address_infos/_form.html.erb
<div class="form-group row">
    <div class="col-sm-6 mb-3 mb-sm-0">
        <span class="required-input">
            <%= obj.text_field :nationality, class: 'form-control',
            placeholder: t('address_infos.nationality') %>
        </span>
    </div>

    <div class="col-sm-6">
        <span class="required-input">
            <%= obj.text_field :province, class: 'form-control',
            placeholder: t('address_infos.province') %>
        </span>
    </div>
</div>
<div class="form-group row">
    <div class="col-sm-6 mb-3 mb-sm-0">
        <span class="required-input">
            <%= obj.text_field :city, class: 'form-control',
            placeholder: t('address_infos.city') %>
        </span>
    </div>

    <div class="col-sm-6">
        <span class="required-input">
            <%= obj.text_field :remaining_address, class: 'form-control',
            placeholder: t('address_infos.remaining_address') %>
        </span>
    </div>
</div>
<div class="form-group row">
    <div class="col-sm-6 mb-3 mb-sm-0">
        <span class="required-input">
            <%= obj.text_field :country, class: 'form-control',
            placeholder: t('address_infos.current_country') %>
        </span>
    </div>

    <div class="col-sm-6">
        <span class="required-input">
            <%= obj.text_field :post_cd, class: 'form-control',
            placeholder: t('address_infos.current_zipcode') %>
        </span>
    </div>
</div>
<div class="form-group row">
    <!--<div class="col-sm-6 mb-3 mb-sm-0">
        <%= obj.email_field :mail_id, class: 'form-control',
        placeholder: t('address_infos.mail_id') %>
    </div>-->

    <div class="col-sm-6">
        <span class="required-input">
            <%= obj.telephone_field :phone_no, class: 'form-control',
            placeholder: t('address_infos.contact_number') %>
        </span>
    </div>
</div>
<div class="form-group row">
    <div class="col-sm-6 mb-3 mb-sm-0">
        <span class="nonrequired-input">
            <%= obj.text_field :linkedIn_url, class: 'form-control',
            placeholder: t('address_infos.linkedIn_url') %>
        </span>
    </div>

    <div class="col-sm-6">
        <span class="nonrequired-input">
            <%= obj.text_field :twitter_url, class: 'form-control',
            placeholder: t('address_infos.twitter_url') %>
        </span>
    </div>
</div>
<div class="form-group row">
    <div class="col-sm-6 mb-3 mb-sm-0">
        <span class="nonrequired-input">
            <%= obj.select(:hosting_service, Address.hosting_services, 
                {}, {class: "form-control", :onchange => "selectHostingService()" }) %>
        </span>
    </div>

    <div class="col-sm-6">
        <span class="nonrequired-input">
            <%= obj.text_field :repository_url, class: 'form-control',
            placeholder: t('address_infos.repository_url') %>
        </span>
    </div>
</div>

app/views/address_infos/edit.html.erb
<%= render 'layouts/errors', obj: @address %>
<h1 class="h4 text-gray-900 mb-4"><%= t('address_infos.title') %></h1>
<%= form_with scope: :address, url: update_address_infos_path, local: true, html: { class: 'user' } do |f| %>
  <%= render 'address_infos/form', obj: f %>
  <div class="form-group row">
      <div class="col-sm-12 ">
          <%= f.submit t('common.submit'), class: 'btn btn-secondary float-right'  %>
      </div>
  </div>
<% end %>

app/views/address_infos/new.html.erb
<%= render 'layouts/errors', obj: @address %>
<h1 class="h4 text-gray-900 mb-4"><%= t('address_infos.title') %></h1>
<%= form_with scope: :address, url: create_address_infos_path, local: true, html: { class: 'user' } do |f| %>
  <%= render 'address_infos/form', obj: f %>
  <div class="form-group row">
      <div class="col-sm-12 ">
          <%= link_to t('common.back'), new_personal_info_path, class: 'btn btn-secondary' %>
          <%= f.submit t('common.next'), class: 'btn btn-secondary float-right'  %>
      </div>
  </div>
<% end %>