config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
         :skip => [:registrations]

  devise_scope :user do
    get "user/sign_up", to: "users/registrations#new", as: :new_user_registration
    post "user/sign_up", to: "users/registrations#create", as: :user_registration
  end

  root 'welcome#index'
  match '/404', to: 'errors#not_found', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all
  resources :personal_infos, only: [:new, :edit]
  resources :address_infos, only: [:new, :edit]
  resources :work_infos, only: [:new, :edit]
  resources :education_infos, only: [:new, :edit]
  resources :project_infos, only: [:new, :edit]
  resources :resumes, only: [:show]
  resources :welcome, only: [:destroy]
  get 'settings', to: 'welcome#settings'
  get 'about', to: 'welcome#about'
  get 'privacy_policy', to: 'welcome#privacy_policy'
  get 'add_new_education', to: 'education_infos#add_new_education'
  get 'add_new_work', to: 'work_infos#add_new_work'
  get 'add_new_project', to: 'project_infos#add_new_project'
  get 'delete_education', to: 'education_infos#delete_education'
  get 'delete_work', to: 'work_infos#delete_work'
  get 'delete_project', to: 'project_infos#delete_project'
  get 'skip_continue', to: 'project_infos#skip_continue'
  post '/personal_infos/new', to: 'personal_infos#create', as: 'create_personal_infos'
  post '/personal_infos/:id/edit', to: 'personal_infos#update', as: 'update_personal_infos'
  post '/address_infos/new', to: 'address_infos#create', as: 'create_address_infos'
  post '/address_infos/:id/edit', to: 'address_infos#update', as: 'update_address_infos'
  post '/education_infos/new', to: 'education_infos#create', as: 'create_education_infos'
  post '/education_infos/:id/edit', to: 'education_infos#update', as: 'update_education_infos'
  post '/work_infos/new', to: 'work_infos#create', as: 'create_work_infos'
  post '/work_infos/:id/edit', to: 'work_infos#update', as: 'update_work_infos'
  post '/project_infos/new', to: 'project_infos#create', as: 'create_project_infos'
  post '/project_infos/:id/edit', to: 'project_infos#update', as: 'update_project_infos'
# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/work_infos_controller.rb
# frozen_string_literal: true

class WorkInfosController < ApplicationController
  before_action :initialize_error_messages, only: %i[new edit create update]
  before_action :initialize_work_infos, only: %i[new edit]

  def new; end

  def edit; end

  def create
    registration_succeeded? ? (redirect_to new_project_info_path) : (render 'new')
  end

  def update
    if registration_succeeded?
      flash[:notice] = t('work_infos.update_success_message')
      redirect_to root_path
    else
      render 'edit'
    end
  end

  def add_new_work
    @index = params[:work_index]
    respond_to do |format|
      format.js { render partial: 'work_infos/add_work' }
    end
  end

  def delete_work
    @index = params[:work_index]
    respond_to do |format|
      format.js { render partial: 'work_infos/delete_work' }
    end
  end

  private

  def work_params(params)
    params.permit(:company_name, :designation, :work_from,
                  :work_to, :job_description)
  end

  def initialize_error_messages
    @error_messages = []
  end

  def initialize_work_infos
    if current_user.works.exists?
      @works = current_user.works
      @record_count = @works.ids.length
    else
      @works = []
      @record_count = 0
    end
  end

  def error_messages(error_record)
    error_record.errors.full_messages.each do |msg|
      @error_messages.push(msg)
    end
  end

  def set_work_records
    @works = []
    params[:works].each do |_id, attributes|
      @works.push(current_user.works.new(work_params(attributes)))
    end
    @works
  end

  def registration_succeeded?
    submitting_records = set_work_records
    success = []
    Work.transaction do
      current_user.works.delete_all if current_user.works.exists?
      success = submitting_records.map(&:save)
      unless success.all?
        errored = submitting_records.reject { |record| record.errors.blank? }
        errored.each { |error_record| error_messages(error_record) }
        raise ActiveRecord::Rollback
      end
    end
    @error_messages.uniq!
    success.all?
  end
end

app/helpers/work_infos_helper.rb
# frozen_string_literal: true

module WorkInfosHelper
end

app/views/work_infos/_add_work.js.erb
document.getElementById('newwork').insertAdjacentHTML('beforeend', '<%= j render 'work_infos/work.html' %>');
if(++document.getElementById('submittingrecordcount').value > "0"){
    document.getElementById('submit').style.display = "block";
}

app/views/work_infos/_addwork.js.erb
document.getElementById('newwork').insertAdjacentHTML('beforeend', '<%= j render 'work_infos/work.html' %>');
if(<%= WorkInfosController.class_variable_get(:@@submitting_records) %> > "0"){
    document.getElementById('submit').style.display = "block";
}

app/views/work_infos/_delete_work.js.erb
document.getElementById('works<%= @index %>').remove();
if(--document.getElementById('submittingrecordcount').value == 0){
    document.getElementById('submit').style.display = "none";
}

app/views/work_infos/_form.html.erb
<% @works.each.with_index(1) do |work,index| %>
    <div id="works<%= index %>">
        <div class="form-group row">
            <div class="col-sm-6 mb-3 mb-sm-0">
                <span class="required-input">
                    <%= text_field_tag "works[#{index}][company_name]", work.company_name, 
                        class: 'form-control form-control-user', placeholder: t('work_infos.company_name') %>
                </span>
            </div>

            <div class="col-sm-6">
                <span class="required-input">
                    <%= text_field_tag "works[#{index}][designation]", work.designation,
                        class: 'form-control form-control-user', placeholder: t('work_infos.designation') %>
                </span>
            </div>
        </div>
        <div class="form-group row">
            <div class="col-sm-6 mb-3 mb-sm-0">
                <span class="required-input">
                    <%= label_tag t('common.from') %>
                    <%= date_field_tag "works[#{index}][work_from]", work.work_from,
                        max: Date.today, class: 'form-control form-control-user' %>
                </span>
            </div>

            <div class="col-sm-6">
                <span class="nonrequired-input">
                    <%= label_tag t('common.to')%>
                    <%= date_field_tag "works[#{index}][work_to]", work.work_to, 
                        max: Date.today, class: 'form-control form-control-user' %>
                </span>
            </div>
        </div>
        <div class="form-group">
            <span class="required-input">
                <%= text_area_tag "works[#{index}][job_description]", work.job_description, 
                    class: 'form-control form-control-textarea', placeholder: t('work_infos.job_description'), size: "50x8" %>
            </span>
        </div>
        <div class="form-group row">
            <div class="col-sm-12 ">
                <%= link_to t('work_infos.delete_button'), delete_work_path(:work_index => index),
                    method: :get ,remote: true, name: 'delete_button', class: 'btn btn-secondary btn-user float-right' %>
            </div>
        </div>
        <hr>
    </div>
    <% if @works.last == work %>
        <div id="newwork">
        </div>
    <% end %>
<% end %>
<%= hidden_field_tag 'submittingrecordcount', @record_count %>
<%= hidden_field_tag 'workindex', @record_count %>
<% if @works.empty?() %>
    <div id="newwork">
    </div>
<% end %>
<div class="form-group row">
    <div class="col-sm-12 ">
        <%= button_tag t('work_infos.add_button'), type: 'button', onclick: 'addWork()', class: 'btn btn-secondary btn-user' %>
        <%= submit_tag t('common.submit'), id: 'submit', class: 'btn btn-secondary btn-user float-right', style: @works.empty?() ? "display:none" : "" %>
    </div>
</div>

app/views/work_infos/_work.html.erb
<div id="works<%= @index %>">
    <div class="form-group row">
        <div class="col-sm-6 mb-3 mb-sm-0">
            <span class="required-input">
                <input type="text" name="works[<%= @index %>][company_name]" id="works_<%= @index %>_company_name"
                class="form-control form-control-user" placeholder="<%= t('work_infos.company_name') %>"/>
            </span>
        </div>

        <div class="col-sm-6">
            <span class="required-input">
                <input type="text" name="works[<%= @index %>][designation]" id="works_<%= @index %>_designation"
                class="form-control form-control-user" placeholder="<%= t('work_infos.designation') %>" />
            </span>
        </div>
    </div>

    <div class="form-group row">
        <div class="col-sm-6 mb-3 mb-sm-0">
            <span class="required-input">
                <label for="from_date"><%= t('common.from') %></label>
                <input type="date" name="works[<%= @index %>][work_from]" id="works_<%= @index %>_work_from" 
                    max='<%= Date.today %>', class="form-control form-control-user"/>
            </span>
        </div>

        <div class="col-sm-6">
            <span class="nonrequired-input">
                <label for="to_date"><%= t('common.to') %></label>
                <input type="date" name="works[<%= @index %>][work_to]" id="works_<%= @index %>work_to" 
                    max='<%= Date.today %>', class="form-control form-control-user"/>
            </span>
        </div>
    </div>

    <div class="form-group">
        <span class="required-input">
            <textarea name="works[<%= @index %>][job_description]" id="works_<%= @index %>_job_description"
            class="form-control form-control-textarea" rows="8" cols="50" placeholder="<%= t('work_infos.job_description') %>"></textarea>
        </span>
    </div>

    <div class="form-group row">
        <div class="col-sm-12 ">
            <%= link_to t('work_infos.delete_button'), delete_work_path(:work_index => @index),
                         method: :get ,remote: true, name: 'delete_button', class: 'btn btn-secondary btn-user float-right' %>
        </div>
    </div>
    <hr>
</div>

app/views/work_infos/edit.html.erb
<%= render 'layouts/multiple_record_errors', obj: @error_messages %>
<h1 class="h4 text-gray-900 mb-4"><%= t('work_infos.title')%></h1>
<%= form_tag update_work_infos_path(method: :post) do %>
    <%= render 'work_infos/form' %>
<% end %>

app/views/work_infos/new.html.erb
<%= render 'layouts/multiple_record_errors', obj: @error_messages %>
<h1 class="h4 text-gray-900 mb-4"><%= t('work_infos.title')%></h1>
<%= form_tag create_work_infos_path(method: :post) do %>
    <%= render 'work_infos/form' %>
<% end %>